# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170915_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='news',
            name='body2',
            field=ckeditor.fields.RichTextField(default='请编辑内容'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
