# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170916_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publish',), 'verbose_name_plural': '内容'},
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('product', 'Product'), ('employment', 'Employment')], default='news', max_length=10),
        ),
    ]
