# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170916_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='请编辑内容'),
        ),
    ]
