# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_news_body2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Content'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='body2',
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='请编辑内容'),
        ),
    ]
