# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170919_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'News')], default='news', max_length=10),
        ),
    ]
