# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 03:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20170930_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('employment', 'Employment')], default='employment', max_length=10)),
                ('title', models.CharField(default='请编辑职位名称', max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('profession', models.TextField(default='请编辑专业要求')),
                ('education', models.TextField(default='请编辑学历要求')),
                ('location', models.TextField(default='请编辑工作地点')),
                ('responsibility', ckeditor_uploader.fields.RichTextUploadingField(default='请编辑岗位职责')),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField(default='请编辑任职要求')),
                ('add_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='请编辑补充信息，可以为空')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employment',
                'ordering': ('-publish',),
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='intro',
            field=models.TextField(default='请编辑简介'),
        ),
    ]
